import { MindMap, MindMapNode } from '../types';

export const COLORS = {
  purple: { bg: '#8B5CF6', text: '#FFFFFF', border: '#7C3AED' },
  blue: { bg: '#3B82F6', text: '#FFFFFF', border: '#2563EB' },
  cyan: { bg: '#06B6D4', text: '#FFFFFF', border: '#0891B2' },
  emerald: { bg: '#10B981', text: '#FFFFFF', border: '#059669' },
  amber: { bg: '#F59E0B', text: '#FFFFFF', border: '#D97706' },
  orange: { bg: '#F97316', text: '#FFFFFF', border: '#EA580C' },
  rose: { bg: '#F43F5E', text: '#FFFFFF', border: '#E11D48' },
  indigo: { bg: '#6366F1', text: '#FFFFFF', border: '#4F46E5' },
  slate: { bg: '#64748B', text: '#FFFFFF', border: '#475569' },
  
  // Pastel variations for sub-nodes
  purpleLight: { bg: '#F5F3FF', text: '#5B21B6', border: '#DDD6FE' },
  blueLight: { bg: '#EFF6FF', text: '#1E40AF', border: '#DBEAFE' },
  cyanLight: { bg: '#ECFEFF', text: '#155E75', border: '#CFFAFE' },
  emeraldLight: { bg: '#ECFDF5', text: '#065F46', border: '#D1FAE5' },
  amberLight: { bg: '#FFFBEB', text: '#92400E', border: '#FEF3C7' },
  orangeLight: { bg: '#FFF7ED', text: '#9A3412', border: '#FFEDD5' },
  roseLight: { bg: '#FFF1F2', text: '#9F1239', border: '#FFE4E6' },
  indigoLight: { bg: '#EEF2FF', text: '#3730A3', border: '#E0E7FF' },
  slateLight: { bg: '#F8FAFC', text: '#334155', border: '#E2E8F0' },
};

export const COLOR_PALETTE = [
  '#8B5CF6', '#3B82F6', '#06B6D4', '#10B981', '#F59E0B', '#F97316', '#F43F5E', '#6366F1', '#64748B',
  '#ECFDF5', '#F5F3FF', '#EFF6FF', '#EEF2FF', '#FFF7ED', '#FFE4E6', '#FFFFFF', '#000000'
];

export function createDefaultMindMap(): MindMap {
  const rootId = 'root-node';
  const branch1Id = 'branch-1';
  const branch2Id = 'branch-2';
  const branch3Id = 'branch-3';
  const branch4Id = 'branch-4';

  const nodes: MindMapNode[] = [
    // Root Node
    {
      id: rootId,
      text: 'Novo Projeto 🚀',
      x: 0,
      y: 0,
      parentId: null,
      color: COLORS.purple.bg,
      textColor: COLORS.purple.text,
      borderColor: COLORS.purple.border,
      shape: 'pill',
      fontSize: 20,
      isBold: true,
      isItalic: false,
    },
    
    // Main Branch 1 - Pesquisa
    {
      id: branch1Id,
      text: 'Pesquisa & Planejamento 💡',
      x: -240,
      y: -100,
      parentId: rootId,
      color: COLORS.amber.bg,
      textColor: COLORS.amber.text,
      borderColor: COLORS.amber.border,
      shape: 'rounded',
      fontSize: 15,
      isBold: true,
      isItalic: false,
      lineColor: COLORS.amber.bg,
      lineWidth: 3,
    },
    {
      id: 'sub-1a',
      text: 'Análise de Concorrentes 📊',
      x: -440,
      y: -150,
      parentId: branch1Id,
      color: COLORS.amberLight.bg,
      textColor: COLORS.amberLight.text,
      borderColor: COLORS.amberLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.amber.bg,
      lineWidth: 2,
    },
    {
      id: 'sub-1b',
      text: 'Entrevistas de Usuários 👥',
      x: -440,
      y: -50,
      parentId: branch1Id,
      color: COLORS.amberLight.bg,
      textColor: COLORS.amberLight.text,
      borderColor: COLORS.amberLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.amber.bg,
      lineWidth: 2,
    },

    // Main Branch 2 - Design
    {
      id: branch2Id,
      text: 'Design da Experiência 🎨',
      x: 240,
      y: -100,
      parentId: rootId,
      color: COLORS.rose.bg,
      textColor: COLORS.rose.text,
      borderColor: COLORS.rose.border,
      shape: 'rounded',
      fontSize: 15,
      isBold: true,
      isItalic: false,
      lineColor: COLORS.rose.bg,
      lineWidth: 3,
    },
    {
      id: 'sub-2a',
      text: 'Paleta de Cores 🌈',
      x: 440,
      y: -150,
      parentId: branch2Id,
      color: COLORS.roseLight.bg,
      textColor: COLORS.roseLight.text,
      borderColor: COLORS.roseLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.rose.bg,
      lineWidth: 2,
    },
    {
      id: 'sub-2b',
      text: 'Protótipos Interativos 📱',
      x: 440,
      y: -50,
      parentId: branch2Id,
      color: COLORS.roseLight.bg,
      textColor: COLORS.roseLight.text,
      borderColor: COLORS.roseLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.rose.bg,
      lineWidth: 2,
    },

    // Main Branch 3 - Dev
    {
      id: branch3Id,
      text: 'Desenvolvimento 💻',
      x: -240,
      y: 120,
      parentId: rootId,
      color: COLORS.emerald.bg,
      textColor: COLORS.emerald.text,
      borderColor: COLORS.emerald.border,
      shape: 'rounded',
      fontSize: 15,
      isBold: true,
      isItalic: false,
      lineColor: COLORS.emerald.bg,
      lineWidth: 3,
    },
    {
      id: 'sub-3a',
      text: 'Modelagem do Banco 🗄️',
      x: -440,
      y: 70,
      parentId: branch3Id,
      color: COLORS.emeraldLight.bg,
      textColor: COLORS.emeraldLight.text,
      borderColor: COLORS.emeraldLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.emerald.bg,
      lineWidth: 2,
    },
    {
      id: 'sub-3b',
      text: 'Componentes UI / React ⚛️',
      x: -440,
      y: 170,
      parentId: branch3Id,
      color: COLORS.emeraldLight.bg,
      textColor: COLORS.emeraldLight.text,
      borderColor: COLORS.emeraldLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.emerald.bg,
      lineWidth: 2,
    },

    // Main Branch 4 - Lançamento
    {
      id: branch4Id,
      text: 'Crescimento & Marketing 🚀',
      x: 240,
      y: 120,
      parentId: rootId,
      color: COLORS.blue.bg,
      textColor: COLORS.blue.text,
      borderColor: COLORS.blue.border,
      shape: 'rounded',
      fontSize: 15,
      isBold: true,
      isItalic: false,
      lineColor: COLORS.blue.bg,
      lineWidth: 3,
    },
    {
      id: 'sub-4a',
      text: 'Campanha Social Media 📢',
      x: 440,
      y: 70,
      parentId: branch4Id,
      color: COLORS.blueLight.bg,
      textColor: COLORS.blueLight.text,
      borderColor: COLORS.blueLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.blue.bg,
      lineWidth: 2,
    },
    {
      id: 'sub-4b',
      text: 'E-mail Marketing ✉️',
      x: 440,
      y: 170,
      parentId: branch4Id,
      color: COLORS.blueLight.bg,
      textColor: COLORS.blueLight.text,
      borderColor: COLORS.blueLight.border,
      shape: 'rectangle',
      fontSize: 13,
      isBold: false,
      isItalic: false,
      lineColor: COLORS.blue.bg,
      lineWidth: 2,
    }
  ];

  return {
    id: 'demo-map',
    name: 'Planejamento do Meu Projeto 🎯',
    nodes,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    themeColor: '#8B5CF6',
    gridType: 'dots',
    lineType: 'curved'
  };
}
